version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      
      - run:
          name: Add Google Cloud SDK GPG Key
          command: |
            # Add the Google Cloud SDK source to the APT sources list
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
            # Download and add the GPG key
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null

      - run:
          name: Update APT Package Index
          command: sudo apt-get update

      - run:
          name: Install Java 17
          command: sudo apt-get install -y openjdk-17-jdk

      - run:
          name: Set JAVA_HOME
          command: echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV

      - run:
          name: Set GRADLE_LOCAL_JAVA_HOME
          command: echo 'export GRADLE_LOCAL_JAVA_HOME=$JAVA_HOME' >> $BASH_ENV

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - restore_cache:
          key: android-orb-v1-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      - run:
          name: Run Build
          command: ./gradlew build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
