version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.12  # Ensure this image supports Java 17

    steps:
      - checkout

      - run:
          name: Install JetBrains Runtime 17.0.11
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk  # This installs the JDK

      - run:
          name: Set JAVA_HOME
          command: echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV

      - run:
          name: Set GRADLE_LOCAL_JAVA_HOME
          command: echo 'export GRADLE_LOCAL_JAVA_HOME=$JAVA_HOME' >> $BASH_ENV

      - restore_cache:
          key: android-orb-v1-{{ checksum "build.gradle" }}

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Create Local Properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - run:
          name: Accept Android SDK Licenses
          command: (yes || true) | sdkmanager --licenses

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      - run:
          name: Run Build
          command: ./gradlew build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
