version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      
      - run:
          name: List Project Files
          command: ls -R  # Untuk debugging, pastikan file ada

      - restore_cache:
          key: android-orb-v1-{{ checksum "app/build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "favorite/build.gradle" }}

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: 'android-orb-v1-{{ epoch }}-{{ checksum "app/build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "favorite/build.gradle" }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      - run:
          name: Run Build
          command: ./gradlew build  # Membangun seluruh proyek

      - store_artifacts: 
          path: app/build/reports
          destination: reports

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
